[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
opacity = 0.8
blur = true
startup_mode = "Maximized"
padding = {x = 10, y = 5}

[general]
live_config_reload = true

[selection]
save_to_clipboard = true

[terminal]
shell = "zsh"
